//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARSWpfApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsertUser", Namespace="http://schemas.datacontract.org/2004/07/ARSWcfService")]
    [System.SerializableAttribute()]
    public partial class InsertUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsAdmin {
            get {
                return this.IsAdminField;
            }
            set {
                if ((this.IsAdminField.Equals(value) != true)) {
                    this.IsAdminField = value;
                    this.RaisePropertyChanged("IsAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPassword {
            get {
                return this.UserPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPasswordField, value) != true)) {
                    this.UserPasswordField = value;
                    this.RaisePropertyChanged("UserPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsertFlight", Namespace="http://schemas.datacontract.org/2004/07/ARSWcfService")]
    [System.SerializableAttribute()]
    public partial class InsertFlight : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArrivalAirportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArrivalTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartureAirportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartureDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartureTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EconomyClassPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstClassPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlightNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeatingCapacityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArrivalAirport {
            get {
                return this.ArrivalAirportField;
            }
            set {
                if ((object.ReferenceEquals(this.ArrivalAirportField, value) != true)) {
                    this.ArrivalAirportField = value;
                    this.RaisePropertyChanged("ArrivalAirport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArrivalTime {
            get {
                return this.ArrivalTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ArrivalTimeField, value) != true)) {
                    this.ArrivalTimeField = value;
                    this.RaisePropertyChanged("ArrivalTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartureAirport {
            get {
                return this.DepartureAirportField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartureAirportField, value) != true)) {
                    this.DepartureAirportField = value;
                    this.RaisePropertyChanged("DepartureAirport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartureDate {
            get {
                return this.DepartureDateField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartureDateField, value) != true)) {
                    this.DepartureDateField = value;
                    this.RaisePropertyChanged("DepartureDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartureTime {
            get {
                return this.DepartureTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartureTimeField, value) != true)) {
                    this.DepartureTimeField = value;
                    this.RaisePropertyChanged("DepartureTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EconomyClassPrice {
            get {
                return this.EconomyClassPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.EconomyClassPriceField, value) != true)) {
                    this.EconomyClassPriceField = value;
                    this.RaisePropertyChanged("EconomyClassPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstClassPrice {
            get {
                return this.FirstClassPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstClassPriceField, value) != true)) {
                    this.FirstClassPriceField = value;
                    this.RaisePropertyChanged("FirstClassPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlightNumber {
            get {
                return this.FlightNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.FlightNumberField, value) != true)) {
                    this.FlightNumberField = value;
                    this.RaisePropertyChanged("FlightNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeatingCapacity {
            get {
                return this.SeatingCapacityField;
            }
            set {
                if ((this.SeatingCapacityField.Equals(value) != true)) {
                    this.SeatingCapacityField = value;
                    this.RaisePropertyChanged("SeatingCapacity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsertSeat", Namespace="http://schemas.datacontract.org/2004/07/ARSWcfService")]
    [System.SerializableAttribute()]
    public partial class InsertSeat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlightNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeatNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlightNumber {
            get {
                return this.FlightNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.FlightNumberField, value) != true)) {
                    this.FlightNumberField = value;
                    this.RaisePropertyChanged("FlightNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SeatNumber {
            get {
                return this.SeatNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SeatNumberField, value) != true)) {
                    this.SeatNumberField = value;
                    this.RaisePropertyChanged("SeatNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUser", ReplyAction="http://tempuri.org/IService1/AddUserResponse")]
        string AddUser(ARSWpfApp.ServiceReference1.InsertUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUser", ReplyAction="http://tempuri.org/IService1/AddUserResponse")]
        System.Threading.Tasks.Task<string> AddUserAsync(ARSWpfApp.ServiceReference1.InsertUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddFlight", ReplyAction="http://tempuri.org/IService1/AddFlightResponse")]
        string AddFlight(ARSWpfApp.ServiceReference1.InsertFlight flight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddFlight", ReplyAction="http://tempuri.org/IService1/AddFlightResponse")]
        System.Threading.Tasks.Task<string> AddFlightAsync(ARSWpfApp.ServiceReference1.InsertFlight flight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSignInCredentials", ReplyAction="http://tempuri.org/IService1/GetSignInCredentialsResponse")]
        System.Data.DataTable GetSignInCredentials(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSignInCredentials", ReplyAction="http://tempuri.org/IService1/GetSignInCredentialsResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetSignInCredentialsAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllFlights", ReplyAction="http://tempuri.org/IService1/GetAllFlightsResponse")]
        System.Data.DataTable GetAllFlights();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllFlights", ReplyAction="http://tempuri.org/IService1/GetAllFlightsResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllFlightsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMyFlights", ReplyAction="http://tempuri.org/IService1/GetMyFlightsResponse")]
        System.Data.DataTable GetMyFlights(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMyFlights", ReplyAction="http://tempuri.org/IService1/GetMyFlightsResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetMyFlightsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddSeat", ReplyAction="http://tempuri.org/IService1/AddSeatResponse")]
        string AddSeat(ARSWpfApp.ServiceReference1.InsertSeat seat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddSeat", ReplyAction="http://tempuri.org/IService1/AddSeatResponse")]
        System.Threading.Tasks.Task<string> AddSeatAsync(ARSWpfApp.ServiceReference1.InsertSeat seat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSelectedSeats", ReplyAction="http://tempuri.org/IService1/GetSelectedSeatsResponse")]
        System.Data.DataTable GetSelectedSeats(string flightName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSelectedSeats", ReplyAction="http://tempuri.org/IService1/GetSelectedSeatsResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetSelectedSeatsAsync(string flightName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ARSWpfApp.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ARSWpfApp.ServiceReference1.IService1>, ARSWpfApp.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddUser(ARSWpfApp.ServiceReference1.InsertUser user) {
            return base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task<string> AddUserAsync(ARSWpfApp.ServiceReference1.InsertUser user) {
            return base.Channel.AddUserAsync(user);
        }
        
        public string AddFlight(ARSWpfApp.ServiceReference1.InsertFlight flight) {
            return base.Channel.AddFlight(flight);
        }
        
        public System.Threading.Tasks.Task<string> AddFlightAsync(ARSWpfApp.ServiceReference1.InsertFlight flight) {
            return base.Channel.AddFlightAsync(flight);
        }
        
        public System.Data.DataTable GetSignInCredentials(string username, string password) {
            return base.Channel.GetSignInCredentials(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetSignInCredentialsAsync(string username, string password) {
            return base.Channel.GetSignInCredentialsAsync(username, password);
        }
        
        public System.Data.DataTable GetAllFlights() {
            return base.Channel.GetAllFlights();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllFlightsAsync() {
            return base.Channel.GetAllFlightsAsync();
        }
        
        public System.Data.DataTable GetMyFlights(string username) {
            return base.Channel.GetMyFlights(username);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetMyFlightsAsync(string username) {
            return base.Channel.GetMyFlightsAsync(username);
        }
        
        public string AddSeat(ARSWpfApp.ServiceReference1.InsertSeat seat) {
            return base.Channel.AddSeat(seat);
        }
        
        public System.Threading.Tasks.Task<string> AddSeatAsync(ARSWpfApp.ServiceReference1.InsertSeat seat) {
            return base.Channel.AddSeatAsync(seat);
        }
        
        public System.Data.DataTable GetSelectedSeats(string flightName) {
            return base.Channel.GetSelectedSeats(flightName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetSelectedSeatsAsync(string flightName) {
            return base.Channel.GetSelectedSeatsAsync(flightName);
        }
    }
}
